name: Ksu
on:
  workflow_dispatch:

jobs:
  ci-test:
    name: ci-ksu
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Ksu CI
      uses: ./
      with:
          kernel-url: https://github.com/Vynxid/android_kernel_xiaomi_sm8150_419
          kernel-branch: lineage-23.0_vayu
          config: vendor/sm8150-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 15
          aosp-clang-version: r547379
          ksu: true
          ksu-version: nongki
          ksu-other: true
          ksu-url: https://github.com/SukiSU-Ultra/SukiSU-Ultra
          lxc: true
          lxc-patch: true
          nethunter: false
          nethunter-patch: false
          bbrplus: true
          zram: true
          anykernel3: true
